export const FORM_SET_INDEX_AT = 'FORM_SET_INDEX_AT';
export const FORM_SET_NUMBER_OF_FORMS = 'FORM_SET_NUMBER_OF_FORMS';

export const USER_SET_USER = 'USER_SET_USER';

export const ROOMS_SET_ROOMS = 'ROOMS_SET_ROOMS';
export const ROOMS_SET_AVAILABLE_ROOMS = 'ROOMS_SET_AVAILABLE_ROOMS';

export const APP_IS_LOADING = 'APP_IS_LOADING';

export const DATES_SET_ENTRY_DATE = 'DATES_SET_ENTRY_DATE';
export const DATES_SET_LEAVING_DATE = 'DATES_SET_LEAVING_DATE';
export const DATES_SET_NUMBER_OF_NIGHTS = 'DATES_SET_NUMBER_OF_NIGHTS';

export const PAYMENT_SET_TOTAL = 'PAYMENT_SET_TOTAL';
export const PAYMENT_SET_PAID = 'PAYMENT_SET_PAID';
export const PAYMENT_SET_INFO = 'PAYMENT_SET_INFO';
