name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: docker build server
        run: |
          docker build ./server -t imariel2d/reservaciones_server
      - name: docker build webapp
        run: |
          docker build ./webapp -t imariel2d/reservaciones_webapp
      - name: docker push
        run: |
          docker push imariel2d/reservaciones_server
          docker push imariel2d/reservaciones_webapp