name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build server
      run: |
        docker build ./server reservaciones_server
    - name: docker build webapp
      run: |
        docker build ./webapp reservaciones_webapp



